name: Build and Deployment Pipeline into Digital Ocean

on:
  push:
    paths-ignore:
      - '**.md'
env:
  IMAGE_NAME: telegrambot
  IMAGE_VERSION: 0.0.${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17.0.7_7-jdk-alpine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build artefact
        run: ./gradlew build

      - uses: actions/upload-artifact@master
        with:
          name: telegram-bot-jar
          path: build/libs/telegrambot.jar

  package:
    runs-on: ubuntu-latest
    container: docker:24.0.2
    # if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: telegram-bot-jar

      - name: Login to Registry
        run: echo ${{secrets.DO_API_TOKEN}} | docker login -u ${{secrets.DO_API_TOKEN}} --password-stdin ${{secrets.DO_REGISTRY}}

      - name: Build Docker Image
        run: docker build -t ${IMAGE_NAME}:${IMAGE_VERSION} .

      - name: Push Docker Image
        # TODO: Need to remove older version (or just use latest)
        run: docker push ${IMAGE_NAME}:${IMAGE_VERSION}

#
#  deploy:
#    runs-on: ubuntu-latest
#    container: //TODO find image
#    needs:
#      - package